### ISSUE TITLE
Any way not to download history archive

### ISSUE THREAD

**Issue by ksemaev** [satoshipay/stellar-core-parallel-catchup#2]
First of all TY for that idea of parallel setup and all suggested compose and script files!

Please advice for those like me - who don't need all `history-result`, how can I safe my traffic and not dowload it?

**Comment by andrenarchy** [comment]
Stellar Core needs to download the history files in order to do the catch up. You may choose to ignore the `history-result` folder eventually if you do not intend to publish it, though.
